### PR TITLE
fix: reset background of button in link component

### LINKED ISSUE #279: Button looking like a link does not have transparent background in windows
image

Reproduced on latest chrome in windows 10 so not isolated to ie/edge

### PR DESCRIPTION
**Pull request by mjmonline**
Closes #279

### CODE REVIEW

File: src/Molecules/Link/Link.tsx [hunk 1]
```diff
@@ -39,6 +39,7 @@ const StyledLink = styled(CleanLink)<LinkProps>`
 
 const StyledButton = styled(NormalizedElements.Button)<LinkProps>`
   ${p => getSharedStyle(p)}
+  background: none;
```
Comment (shmidt-i) [inline src/Molecules/Link/Link.tsx]: I am thinking about adding this in my PR:
```css
  /* resetting button styles */
  border: none;
  margin: 0;
  padding: 0;
  width: auto;
  overflow: visible;

  background: transparent;

  /* Corrects font smoothing for webkit */
  -webkit-font-smoothing: inherit;
  -moz-osx-font-smoothing: inherit;

  /* Corrects inability to style clickable input types in iOS */
  -webkit-appearance: none !important;
  /* resetting button styles end */
```

Comment (mjmonline) [reply src/Molecules/Link/Link.tsx]: Are you thinking in the NormalizedButton file? I believe the `font-smoothing` is outdated, the browsers have gotten updates since then which makes them render better without this rule. Also the `-webkit-appearance` is already defined in the NormalizedButton file.
